
server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-stacktrace: always
  tomcat:
    connection-timeout: 360000
    keep-alive-timeout: 300000
    max-connections: 100


spring:
  application:
    name: adapter-api
  devtools:
    restart:
      enabled: true

logging:
  level:
    web: debug

